#!/bin/bash
set -e

# don't loop if files don't exist
shopt -s nullglob

# exit if TRAVIS_TAG is empty, no need to release anything
if [ -z "${TRAVIS_TAG}" ]; then
  exit 0
fi


# download and untar github-release
wget -nv -O linux-amd64-github-release.bz2 https://github.com/github-release/github-release/releases/download/v0.8.1/linux-amd64-github-release.bz2
bunzip2 linux-amd64-github-release.bz2
mv linux-amd64-github-release github-release
chmod +x github-release

DISTDIR=$(pwd)/skarnet-builder/dist

# get user and repo names
USERNAME=$(echo ${TRAVIS_REPO_SLUG} | cut -d"/" -f1)
REPONAME=$(echo ${TRAVIS_REPO_SLUG} | cut -d"/" -f2)

# release
./github-release release \
  --user "${USERNAME}" \
  --repo "${REPONAME}" \
  --tag "${TRAVIS_TAG##*/}" \
  --name "${TRAVIS_TAG##*/}" \
  --description "$(cat ${DISTDIR}/release.md)"

# manifests
for i in ${DISTDIR}/manifest*.txt; do
  name=$(basename ${i})
  ./github-release upload \
    --user "${USERNAME}" \
    --repo "${REPONAME}" \
    --tag "${TRAVIS_TAG##*/}" \
    --name "${name}" \
    --file "${i}"
done

# skaware binaries
for i in ${DISTDIR}/*.tar.gz; do
  name=$(basename ${i})
  ./github-release upload \
    --user "${USERNAME}" \
    --repo "${REPONAME}" \
    --tag "${TRAVIS_TAG##*/}" \
    --name "${name}" \
    --file "${i}"
done
